"""
ToolpathEngine — Validates and converts raw MotionCommands to ToolpathSegments.

This engine does not read geometry boundaries directly. It consumes the
MotionCommand list produced by MotionPlanner, enforces constraints, and 
outputs clean, validated ToolpathSegment arrays.
"""
from typing import List, Dict, Any
from app.models.schemas import ToolpathSegment, MotionCommand, ToolpathSegmentType

# Only these source strings are allowed on output segments
ALLOWED_SOURCES = {"drill", "contour", "pocket", "boss", "face", "turning"}
BANNED_SOURCES = {
    "debug_wire", "edge_sample", "topology_boundary", "silhouette", "fallback", "outer_wire_sample",
    "hole_center", "outer_wire", "face_boundary", "pocket_boundary", "boss_floor_minus_island", "turning_profile"
}

class ToolpathEngine:
    """
    Core engine responsible for validating physical 3D toolpaths
    from MotionPlanner commands.
    """

    def __init__(self):
        pass

    def generate_toolpaths_from_commands(self, op: Dict[str, Any], commands: List[MotionCommand], limit: int = 15000) -> List[ToolpathSegment]:
        op['toolpath_schema_version'] = 'semantic_v1'
        op_type = op.get('type', 'unknown')
        if op_type in ['legacy_path', 'mock_path', 'fallback_path', 'silhouette_path', 'generic_path', 'unknown', 'blocked']:
            op["status"] = "blocked"
            op.setdefault("parameters", {})["error"] = f"Operation type '{op_type}' is unsupported or blocked."
            return []

        if not commands:
            op["status"] = "error"
            op.setdefault("parameters", {})["error"] = "No motion commands generated by planner."
            return []

        segments: List[ToolpathSegment] = []

        if len(commands) > limit:
            op["status"] = "error"
            op.setdefault("parameters", {})["error"] = f"Command count {len(commands)} exceeds limit {limit}"
            return []

        for cmd in commands:
            if not cmd.operationId or not cmd.featureId or not cmd.toolId or not cmd.setupId:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = "Command validation failed: missing mandatory properties."
                return []
                
            if cmd.source in BANNED_SOURCES:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = f"Command uses banned source: {cmd.source}"
                return []
                
            if cmd.source not in ALLOWED_SOURCES:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = f"Command uses unknown source: {cmd.source}. Allowed: {ALLOWED_SOURCES}"
                return []
                
            raw_legacy_types = {"rapid", "feed", "retract", "arc", "helix"}
            if str(cmd.commandType) in raw_legacy_types or (hasattr(cmd.commandType, 'value') and cmd.commandType.value in raw_legacy_types):
                op["status"] = "blocked"
                op.setdefault("parameters", {})["error"] = f"RAW_SEGMENT_TYPE_BLOCKED: Raw segment type '{cmd.commandType}' is not allowed. Regenerate toolpaths using semantic segment types."
                return []
                
            # If the commandType is not a valid enum member (should be caught by Pydantic, but just in case)
            if not any(cmd.commandType == item.value or cmd.commandType == item for item in ToolpathSegmentType):
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = f"Command uses invalid moveType: {cmd.commandType}."
                return []

            segments.append(
                ToolpathSegment(
                    segmentId=cmd.commandId,
                    moveType=cmd.commandType,
                    start=cmd.start,
                    end=cmd.end,
                    feedrate=cmd.feedrate,
                    spindle=cmd.spindle,
                    toolId=cmd.toolId,
                    operationId=cmd.operationId,
                    featureId=cmd.featureId,
                    setupId=cmd.setupId,
                    source=cmd.source,
                    center=cmd.center,
                    radius=cmd.radius,
                    clockwise=cmd.clockwise,
                    plane=cmd.plane
                )
            )

        return segments
