"""
ToolpathEngine — Validates and converts raw MotionCommands to ToolpathSegments.

This engine does not read geometry boundaries directly. It consumes the
MotionCommand list produced by MotionPlanner, enforces constraints, and 
outputs clean, validated ToolpathSegment arrays.
"""
from typing import List, Dict, Any
from app.models.schemas import ToolpathSegment, MotionCommand, ToolpathSegmentType

# Only these source strings are allowed on output segments
ALLOWED_SOURCES = {"drill", "contour", "pocket", "boss", "face", "turning"}
BANNED_SOURCES = {
    "debug_wire", "edge_sample", "topology_boundary", "silhouette", "fallback", "outer_wire_sample",
    "hole_center", "outer_wire", "face_boundary", "pocket_boundary", "boss_floor_minus_island", "turning_profile"
}

class ToolpathEngine:
    """
    Core engine responsible for validating physical 3D toolpaths
    from MotionPlanner commands.
    """

    def __init__(self):
        pass

    def generate_toolpaths_from_commands(self, op: Dict[str, Any], commands: List[MotionCommand], limit: int = 3000) -> List[ToolpathSegment]:
        if not commands:
            op["status"] = "error"
            op.setdefault("parameters", {})["error"] = "No motion commands generated by planner."
            return []

        segments: List[ToolpathSegment] = []

        if len(commands) > limit:
            op["status"] = "error"
            op.setdefault("parameters", {})["error"] = f"Command count {len(commands)} exceeds limit {limit}"
            return []

        for cmd in commands:
            if not cmd.operationId or not cmd.featureId or not cmd.toolId or not cmd.setupId:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = "Command validation failed: missing mandatory properties."
                return []
                
            if cmd.source in BANNED_SOURCES:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = f"Command uses banned source: {cmd.source}"
                return []
                
            if cmd.source not in ALLOWED_SOURCES:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = f"Command uses unknown source: {cmd.source}. Allowed: {ALLOWED_SOURCES}"
                return []
                
            if cmd.commandType not in ToolpathSegmentType:
                op["status"] = "error"
                op.setdefault("parameters", {})["error"] = f"Command uses invalid moveType: {cmd.commandType}."
                return []

            segments.append(
                ToolpathSegment(
                    segmentId=cmd.commandId,
                    moveType=cmd.commandType,
                    start=cmd.start,
                    end=cmd.end,
                    feedrate=cmd.feedrate,
                    spindle=cmd.spindle,
                    toolId=cmd.toolId,
                    operationId=cmd.operationId,
                    featureId=cmd.featureId,
                    setupId=cmd.setupId,
                    source=cmd.source,
                    center=cmd.center,
                    radius=cmd.radius,
                    clockwise=cmd.clockwise,
                    plane=cmd.plane
                )
            )

        return segments
