import { useEffect } from 'react';
import type { CamFeature } from '@/types/cam';
import { Target, AlertTriangle, XCircle, CheckCircle2, Wand2, ArrowDown, ArrowUp, Zap } from 'lucide-react';

type FeatureOverviewSectionProps = {
    features: CamFeature[];
    activeFeatureId: string | null;
    onFeatureSelect: (id: string | null) => void;
    onAutoGenerate: () => void;
    workflowStage?: string;
    setWorkflowStage?: (v: string) => void;
    onRunFeatureRecognition?: () => void;
    isAutoGenerateDisabled?: boolean;
};

export function FeatureOverviewSection({
    features,
    activeFeatureId,
    onFeatureSelect,
    onAutoGenerate,
    workflowStage,
    setWorkflowStage,
    onRunFeatureRecognition,
    isAutoGenerateDisabled
}: FeatureOverviewSectionProps) {

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (features.length === 0) return;
            if (document.activeElement?.tagName === 'INPUT' || document.activeElement?.tagName === 'TEXTAREA' || document.activeElement?.tagName === 'SELECT') return;

            const currentIndex = activeFeatureId ? features.findIndex(f => f.id === activeFeatureId) : -1;
            
            if (e.key === 'ArrowDown') {
                e.preventDefault();
                const nextIdx = currentIndex === -1 ? 0 : (currentIndex + 1) % features.length;
                onFeatureSelect(features[nextIdx].id);
            } else if (e.key === 'ArrowUp') {
                e.preventDefault();
                const prevIdx = currentIndex === -1 ? features.length - 1 : (currentIndex - 1 + features.length) % features.length;
                onFeatureSelect(features[prevIdx].id);
            }
        };
        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [activeFeatureId, features, onFeatureSelect]);

    if (features.length === 0) {
        return (
            <div className="rounded-xl border border-border/50 p-8 text-center bg-muted/10 text-[12px] text-muted-foreground flex flex-col items-center justify-center min-h-[150px] gap-4 relative overflow-hidden shadow-sm">
                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 to-transparent pointer-events-none" />
                <div className="flex flex-col gap-1 z-10">
                    <span className="text-foreground font-bold tracking-wider uppercase text-[11px]">Feature Analysis Required</span>
                    <span className="opacity-70 text-[11px]">Analyze 3D geometry to extract machinable features.</span>
                </div>
                <button 
                    onClick={() => {
                        if (setWorkflowStage) setWorkflowStage('cam');
                        if (onRunFeatureRecognition) onRunFeatureRecognition();
                    }}
                    className="z-10 mt-2 flex items-center gap-2 px-6 py-2.5 rounded-lg bg-primary hover:bg-primary/90 text-primary-foreground font-bold uppercase tracking-widest text-[10px] shadow-[0_0_15px_rgba(59,130,246,0.3)] hover:shadow-[0_0_25px_rgba(59,130,246,0.5)] transition-all"
                >
                    <Wand2 className="size-3.5" />
                    Run Feature Recognition
                </button>
            </div>
        );
    }

    const typeSummary = features.reduce((acc, feat) => {
        acc[feat.type] = (acc[feat.type] || 0) + 1;
        return acc;
    }, {} as Record<string, number>);

    return (
        <div className="space-y-4 flex flex-col h-full animate-in fade-in duration-300">
            <button 
                onClick={onAutoGenerate}
                disabled={isAutoGenerateDisabled}
                className={`w-full relative group overflow-hidden flex items-center justify-center gap-2 py-3 rounded-xl text-[11px] uppercase tracking-widest font-bold transition-all shadow-sm ${isAutoGenerateDisabled ? 'bg-muted border border-border/50 text-muted-foreground cursor-not-allowed opacity-60' : 'bg-primary/10 hover:bg-primary border border-primary/30 hover:border-primary text-primary hover:text-primary-foreground'}`}
            >
                {!isAutoGenerateDisabled && <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent translate-x-[-100%] group-hover:animate-[shimmer_1.5s_infinite]" />}
                <Zap className="size-4" />
                Auto Generate All Operations
            </button>

            <div className="flex justify-between items-center pb-3 border-b border-border/40">
                <div className="flex gap-2 flex-wrap">
                    {Object.entries(typeSummary).map(([type, count]) => (
                        <div key={type} className="text-[9px] font-bold uppercase tracking-wider bg-muted/30 border border-border/50 px-2 py-1 rounded-md text-muted-foreground">
                            {type.replace('_', ' ')}: {count}
                        </div>
                    ))}
                </div>
                <div className="flex gap-1.5 text-[9px] font-medium uppercase tracking-wider text-muted-foreground/60 items-center bg-muted/20 px-2 py-1 rounded-md border border-border/30">
                    Navigate
                    <div className="flex gap-0.5">
                        <ArrowUp className="size-3" />
                        <ArrowDown className="size-3" />
                    </div>
                </div>
            </div>

            <div className="space-y-2 overflow-y-auto flex-1 pb-20 custom-scrollbar pr-2">
                {features.map((feat) => {
                    const isActive = activeFeatureId === feat.id;
                    return (
                        <div 
                            key={feat.id}
                            className={`p-3.5 rounded-xl cursor-pointer transition-all border ${
                                isActive 
                                    ? 'bg-primary/10 border-primary/50 shadow-sm ring-1 ring-primary/20' 
                                    : 'bg-background/40 hover:bg-muted/30 border-border/50 hover:border-border'
                            }`}
                            onClick={() => onFeatureSelect(isActive ? null : feat.id)}
                        >
                            <div className="flex justify-between items-start mb-2">
                                <div className="flex items-center gap-2 font-medium">
                                    <Target className={`size-4 ${isActive ? 'text-primary' : 'text-muted-foreground/50'}`} />
                                    <span className={`text-[12px] ${isActive ? 'text-primary font-bold' : 'text-foreground/90 font-semibold'}`}>
                                        {feat.name || feat.type.replace(/_/g, ' ')}
                                    </span>
                                </div>
                                <div className="flex items-center gap-1.5">
                                    {feat.status === 'machinable' && <span title="Machinable" className="flex items-center justify-center bg-green-500/10 rounded-full p-1"><CheckCircle2 className="size-3.5 text-green-500" /></span>}
                                    {feat.status === 'limited' && <span title="Limited Accessibility" className="flex items-center justify-center bg-amber-500/10 rounded-full p-1"><AlertTriangle className="size-3.5 text-amber-500" /></span>}
                                    {feat.status === 'not_machinable' && <span title="Not Machinable" className="flex items-center justify-center bg-red-500/10 rounded-full p-1"><XCircle className="size-3.5 text-red-500" /></span>}
                                </div>
                            </div>
                            
                            {(feat.count && feat.count > 1) && (
                                <div className="text-[10px] text-primary/80 mb-2 font-medium bg-primary/10 border border-primary/20 px-2 py-0.5 rounded w-fit">
                                    Group: {feat.count} items
                                </div>
                            )}
                            
                            <div className="flex gap-4 text-[10px]">
                                {(() => {
                                    const dims = feat.dimensions || {};
                                    // If no explicit dimensions object, try to extract from root
                                    if (Object.keys(dims).length === 0) {
                                        const rawFeat = feat as any;
                                        if (rawFeat.diameter !== undefined) dims.diameter = rawFeat.diameter;
                                        if (rawFeat.depth !== undefined) dims.depth = rawFeat.depth;
                                        if (rawFeat.width !== undefined) dims.width = rawFeat.width;
                                        if (rawFeat.length !== undefined) dims.length = rawFeat.length;
                                    }
                                    
                                    return Object.entries(dims).slice(0, 3).map(([key, value]) => {
                                        let displayValue: string | number = value as string | number;
                                        if (typeof value === 'number') {
                                            displayValue = Number.isInteger(value) ? value : value.toFixed(2);
                                        }
                                        return (
                                            <div key={key} className="flex flex-col gap-0.5">
                                                <span className="text-muted-foreground/70 uppercase tracking-wider font-semibold text-[9px]">{key}</span>
                                                <span className="font-mono text-foreground/90 font-medium">{displayValue}mm</span>
                                            </div>
                                        );
                                    });
                                })()}
                            </div>
                        </div>
                    );
                })}
            </div>
        </div>
    );
}
